# Site Settings
baseurl: 		/
title: 			Parkerrr

name: 			Welcome <i>to</i> Parker
description: 	Web Architect and Designer 
url: 			"http://www.parkerrr.com"

paginate: 		10
paginate_path: 	"blog/page:num"

twitter: 		thnkco
email: 			jason@parkerrr.com

disqus: 		parkerrr
analytics: 		UA-XXXXXXX-Y

copyright: 		Copyright 2015 Jason Beaton.	

# Build Settings
permalinks: 	pretty
